### ISSUE TITLE
打开localhost:8080端口，显示数据加载失败？

### ISSUE THREAD

**Issue by ZhaoTim** [chuyun/Design-BMS#1]
看了请求 http://127.0.0.1:3001/admin/list 请求失败了 net::ERR_CONNECTION_REFUSED ，想请教一下大神这是为什么呢？

**Comment by chuyun** [comment]
接口跑起来了？

On 2018年4月18日 +0800 20:47, ZhaoTim <notifications@github.com>, wrote:

看了请求 http://127.0.0.1:3001/admin/list 请求失败了 net::ERR_CONNECTION_REFUSED ，想请教一下大神这是为什么呢？

**Comment by ZhaoTim** [comment]
npm start 以后，项目出现登录的界面啊，并且有碳层说数据加载失败，我全局搜索代码“http://127.0.0.1:3001/admin/list”看到代码中只有关于请求这个接口的代码，并没有发现关于这个接口的后端代码，还是说这个项目本身就没有服务器关于请求的代码呢？？？（react新手，，可能描述的不准确，见谅！。。。）

**Comment by chuyun** [comment]
加一下QQ 781113112


On 2018年4月19日 +0800 23:11, ZhaoTim <notifications@github.com>, wrote:

npm start 以后，项目出现登录的界面啊，并且有碳层说数据加载失败，我全局搜索代码“http://127.0.0.1:3001/admin/list”看到代码中只有关于请求这个接口的代码，并没有发现关于这个接口的后端代码，还是说这个项目本身就没有服务器关于请求的代码呢？？？（react新手，，可能描述的不准确，见谅！。。。）<http://127.0.0.1:3001/admin/list%E2%80%9D%E7%9C%8B%E5%88%B0%E4%BB%A3%E7%A0%81%E4%B8%AD%E5%8F%AA%E6%9C%89%E5%85%B3%E4%BA%8E%E8%AF%B7%E6%B1%82%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3%E7%9A%84%E4%BB%A3%E7%A0%81%EF%BC%8C%E5%B9%B6%E6%B2%A1%E6%9C%89%E5%8F%91%E7%8E%B0%E5%85%B3%E4%BA%8E%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%90%8E%E7%AB%AF%E4%BB%A3%E7%A0%81%EF%BC%8C%E8%BF%98%E6%98%AF%E8%AF%B4%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%9C%AC%E8%BA%AB%E5%B0%B1%E6%B2%A1%E6%9C%89%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%85%B3%E4%BA%8E%E8%AF%B7%E6%B1%82%E7%9A%84%E4%BB%A3%E7%A0%81%E5%91%A2%EF%BC%9F%EF%BC%9F%EF%BC%9F%EF%BC%88react%E6%96%B0%E6%89%8B%EF%BC%8C%EF%BC%8C%E5%8F%AF%E8%83%BD%E6%8F%8F%E8%BF%B0%E7%9A%84%E4%B8%8D%E5%87%86%E7%A1%AE%EF%BC%8C%E8%A7%81%E8%B0%85%EF%BC%81%E3%80%82%E3%80%82%E3%80%82%EF%BC%89>
